/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as MembersRouteImport } from './routes/members'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TutorialsIndexRouteImport } from './routes/tutorials.index'
import { Route as TutorialsSlugRouteImport } from './routes/tutorials.$slug'
import { Route as InstallSlugRouteImport } from './routes/install.$slug'
import { Route as TutorialsSlugInstallRouteImport } from './routes/tutorials.$slug_.install'
import { Route as TutorialsSlugPromptsDotmdRouteImport } from './routes/tutorials.$slug.prompts[.]md'
import { Route as TutorialsSlugBundleDotzipRouteImport } from './routes/tutorials.$slug.bundle[.]zip'
import { Route as ApiAuthGoogleRouteImport } from './routes/api.auth.google'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api.auth.google.callback'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialsIndexRoute = TutorialsIndexRouteImport.update({
  id: '/tutorials/',
  path: '/tutorials/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialsSlugRoute = TutorialsSlugRouteImport.update({
  id: '/tutorials/$slug',
  path: '/tutorials/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallSlugRoute = InstallSlugRouteImport.update({
  id: '/install/$slug',
  path: '/install/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialsSlugInstallRoute = TutorialsSlugInstallRouteImport.update({
  id: '/tutorials/$slug_/install',
  path: '/tutorials/$slug/install',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialsSlugPromptsDotmdRoute =
  TutorialsSlugPromptsDotmdRouteImport.update({
    id: '/prompts.md',
    path: '/prompts.md',
    getParentRoute: () => TutorialsSlugRoute,
  } as any)
const TutorialsSlugBundleDotzipRoute =
  TutorialsSlugBundleDotzipRouteImport.update({
    id: '/bundle.zip',
    path: '/bundle.zip',
    getParentRoute: () => TutorialsSlugRoute,
  } as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthGoogleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/members': typeof MembersRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/install/$slug': typeof InstallSlugRoute
  '/tutorials/$slug': typeof TutorialsSlugRouteWithChildren
  '/tutorials/': typeof TutorialsIndexRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/tutorials/$slug/bundle.zip': typeof TutorialsSlugBundleDotzipRoute
  '/tutorials/$slug/prompts.md': typeof TutorialsSlugPromptsDotmdRoute
  '/tutorials/$slug/install': typeof TutorialsSlugInstallRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/members': typeof MembersRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/install/$slug': typeof InstallSlugRoute
  '/tutorials/$slug': typeof TutorialsSlugRouteWithChildren
  '/tutorials': typeof TutorialsIndexRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/tutorials/$slug/bundle.zip': typeof TutorialsSlugBundleDotzipRoute
  '/tutorials/$slug/prompts.md': typeof TutorialsSlugPromptsDotmdRoute
  '/tutorials/$slug/install': typeof TutorialsSlugInstallRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/members': typeof MembersRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/install/$slug': typeof InstallSlugRoute
  '/tutorials/$slug': typeof TutorialsSlugRouteWithChildren
  '/tutorials/': typeof TutorialsIndexRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/tutorials/$slug/bundle.zip': typeof TutorialsSlugBundleDotzipRoute
  '/tutorials/$slug/prompts.md': typeof TutorialsSlugPromptsDotmdRoute
  '/tutorials/$slug_/install': typeof TutorialsSlugInstallRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/members'
    | '/robots.txt'
    | '/services'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/install/$slug'
    | '/tutorials/$slug'
    | '/tutorials/'
    | '/api/auth/google'
    | '/tutorials/$slug/bundle.zip'
    | '/tutorials/$slug/prompts.md'
    | '/tutorials/$slug/install'
    | '/api/auth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/members'
    | '/robots.txt'
    | '/services'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/install/$slug'
    | '/tutorials/$slug'
    | '/tutorials'
    | '/api/auth/google'
    | '/tutorials/$slug/bundle.zip'
    | '/tutorials/$slug/prompts.md'
    | '/tutorials/$slug/install'
    | '/api/auth/google/callback'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/members'
    | '/robots.txt'
    | '/services'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/install/$slug'
    | '/tutorials/$slug'
    | '/tutorials/'
    | '/api/auth/google'
    | '/tutorials/$slug/bundle.zip'
    | '/tutorials/$slug/prompts.md'
    | '/tutorials/$slug_/install'
    | '/api/auth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  MembersRoute: typeof MembersRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ServicesRoute: typeof ServicesRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  InstallSlugRoute: typeof InstallSlugRoute
  TutorialsSlugRoute: typeof TutorialsSlugRouteWithChildren
  TutorialsIndexRoute: typeof TutorialsIndexRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRouteWithChildren
  TutorialsSlugInstallRoute: typeof TutorialsSlugInstallRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorials/': {
      id: '/tutorials/'
      path: '/tutorials'
      fullPath: '/tutorials/'
      preLoaderRoute: typeof TutorialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorials/$slug': {
      id: '/tutorials/$slug'
      path: '/tutorials/$slug'
      fullPath: '/tutorials/$slug'
      preLoaderRoute: typeof TutorialsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install/$slug': {
      id: '/install/$slug'
      path: '/install/$slug'
      fullPath: '/install/$slug'
      preLoaderRoute: typeof InstallSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorials/$slug_/install': {
      id: '/tutorials/$slug_/install'
      path: '/tutorials/$slug/install'
      fullPath: '/tutorials/$slug/install'
      preLoaderRoute: typeof TutorialsSlugInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorials/$slug/prompts.md': {
      id: '/tutorials/$slug/prompts.md'
      path: '/prompts.md'
      fullPath: '/tutorials/$slug/prompts.md'
      preLoaderRoute: typeof TutorialsSlugPromptsDotmdRouteImport
      parentRoute: typeof TutorialsSlugRoute
    }
    '/tutorials/$slug/bundle.zip': {
      id: '/tutorials/$slug/bundle.zip'
      path: '/bundle.zip'
      fullPath: '/tutorials/$slug/bundle.zip'
      preLoaderRoute: typeof TutorialsSlugBundleDotzipRouteImport
      parentRoute: typeof TutorialsSlugRoute
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof ApiAuthGoogleRoute
    }
  }
}

interface TutorialsSlugRouteChildren {
  TutorialsSlugBundleDotzipRoute: typeof TutorialsSlugBundleDotzipRoute
  TutorialsSlugPromptsDotmdRoute: typeof TutorialsSlugPromptsDotmdRoute
}

const TutorialsSlugRouteChildren: TutorialsSlugRouteChildren = {
  TutorialsSlugBundleDotzipRoute: TutorialsSlugBundleDotzipRoute,
  TutorialsSlugPromptsDotmdRoute: TutorialsSlugPromptsDotmdRoute,
}

const TutorialsSlugRouteWithChildren = TutorialsSlugRoute._addFileChildren(
  TutorialsSlugRouteChildren,
)

interface ApiAuthGoogleRouteChildren {
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
}

const ApiAuthGoogleRouteChildren: ApiAuthGoogleRouteChildren = {
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
}

const ApiAuthGoogleRouteWithChildren = ApiAuthGoogleRoute._addFileChildren(
  ApiAuthGoogleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  MembersRoute: MembersRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ServicesRoute: ServicesRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  InstallSlugRoute: InstallSlugRoute,
  TutorialsSlugRoute: TutorialsSlugRouteWithChildren,
  TutorialsIndexRoute: TutorialsIndexRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRouteWithChildren,
  TutorialsSlugInstallRoute: TutorialsSlugInstallRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
